export const Routes = [
    {
      "id":"1",      
      "from": "Remera",
      "to": "Downtown via Sonatube",
      "operate": "kigali",
      "price": 600,
    },
    {
        "id":"1",      
        "from": "Remera",
        "to": "Kimironko",
        "operate": "kigali",
        "price": 600,
      },
      {
        "id":"1",      
        "from": "Remera",
        "to": "Gikondo",
        "operate": "kigali",
        "price": 600,
      },
      {
        "id":"1",      
        "from": "Remera",
        "to": "Nyabugogo via Gishushu",
        "operate": "kigali",
        "price": 600,
      },
    {
        "id":"2",      
      "from": "Kabuga",
      "to": "Nyabugogo via Sonatube",
      "operate": "kigali",
      "price": 300,
    },
    {
        "id":"2",      
      "from": "Kabuga",
      "to": "Remera",
      "operate": "kigali",
      "price": 300,
    },
    {
        "id":"2",      
      "from": "Kabuga",
      "to": "Downtown",
      "operate": "kigali",
      "price": 300,
    },
    {
        "id":"2",      
      "from": "Kabuga",
      "to": "Kimironko",
      "operate": "kigali",
      "price": 300,
    },
    {
        "id":"2",      
      "from": "Kabuga",
      "to": "Kanombe",
      "operate": "kigali",
      "price": 300,
    },
    {
        "id":"2",      
      "from": "Kabuga",
      "to": "Downtown",
      "operate": "kigali",
      "price": 300,
    },
    {
        "id":"3",      
      "from": "Downtown",
        "to": "Kabeza - Rubirizi via Remera",
        "operate": "kigali",
        "price": 500,
    },
    {
        "id":"4",      
      "from": "Remera",
      "to": "Ndera ku Gasima",
      "operate": "kigali",
      "price": 500,
    },
    {
        "id":"8",      
        "from": "Nyabugogo",
        "to": "Kimironko",
        "operate": "kigali",
        "price": 3406,
    },
    {
        "id":"8",      
        "from": "Nyabugogo",
        "to": "Gikondo",
        "operate": "kigali",
        "price": 3406,
    },
    {
        "id":"8",      
        "from": "Nyabugogo",
        "to": "Kinyinya",
        "operate": "kigali",
        "price": 3406,
    },
    {
        "id":"8",      
        "from": "Nyabugogo",
        "to": "Nyabisindu",
        "operate": "kigali",
        "price": 3406,
    },
    {
        "id":"12",      
        "from": "Nyabugogo",
        "to": "Kabuga",
        "operate": "kigali",
        "price": 3406,
    },
    {
        "id":"48",      
        "from": "Nyabugogo",
        "to": "Remera",
        "operate": "kigali",
        "price": 3406,
    },
    {
        "id":"489",      
        "from": "Nyabugogo",
        "to": "Gisozi",
        "operate": "kigali",
        "price": 3406,
    },
    {
        "id":"5", 
        "from": "Downtown",
        "to": "Nyanza ya Kicukiro via Sonatube",
        "operate": "kigali",
        "price": 400,
    },
    {
        "id":"5", 
        "from": "Downtown",
        "to": "Kimironko",
        "operate": "kigali",
        "price": 400,
    },
    {
        "id":"5", 
        "from": "Downtown",
        "to": "Gisozi",
        "operate": "kigali",
        "price": 400,
    },
    {
        "id":"5", 
        "from": "Downtown",
        "to": "Nyabugogo",
        "operate": "kigali",
        "price": 400,
    },
    {
        "id":"6",      
        "from": "Nyabugogo",
        "to": "Rwimiyaga",
        "operate": "upCountry sides",
        "price": 3406,
    },
    {
        "id":"7",      
        "from": "Nyabugogo",
        "to": "Rusizi Kamembe",
        "operate": "upCountry sides",
        "price": 3406,
    },
    {
        "id":"8",      
        "from": "Nyabugogo",
        "to": "Nyagatare",
        "operate": "upCountry sides",
        "price": 3406,
    },
    {
        "id":"8",      
        "from": "Nyabugogo",
        "to": "Ryabega",
        "operate": "upCountry sides",
        "price": 3406,
    },
    {
        "id":"9",      
        "from": "Nyabugogo",
        "to": "Kibirizi",
        "operate": "upCountry sides",
        "price": 3406,
    },
    {
        "id":"10",      
        "from": "Nyabugogo",
        "to": "Busogo",
        "operate": "upCountry sides",
        "price": 3406,
    },
    {
        "id":"10",      
        "from": "Nyabugogo",
        "to": "Nyatagare",
        "operate": "upCountry sides",
        "price": 3406,
    },
    {
        "id":"11",      
        "from": "Muhanga",
        "to": "Karongi",
        "operate": "upCountry sides",
        "price": 3406,
    },
    {
        "id":"11",      
        "from": "Muhanga",
        "to": "Huye",
        "operate": "upCountry sides",
        "price": 3406,
    },
    {
        "id":"11",      
        "from": "Muhanga",
        "to": "Nyabugog",
        "operate": "upCountry sides",
        "price": 3406,
    },
    {
        "id":"11",      
        "from": "Muhanga",
        "to": "Ruhango",
        "operate": "upCountry sides",
        "price": 3406,
    },
    {
        "id":"11",      
        "from": "Muhanga",
        "to": "Rubavu",
        "operate": "upCountry sides",
        "price": 3406,
    },
    {
        "id":"11",      
        "from": "Muhanga",
        "to": "Rusizi",
        "operate": "upCountry sides",
        "price": 3406,
    },
    {
        "id":"12",      
        "from": "Rubavu",
        "to": "Musanze",
        "operate": "upCountry sides",
        "price": 3406,
    },
    {
        "id":"12",      
        "from": "Rubavu",
        "to": "Karongi",
        "operate": "upCountry sides",
        "price": 3406,
    },
    {
        "id":"12",      
        "from": "Rubavu",
        "to": "Nyabugogo",
        "operate": "upCountry sides",
        "price": 3406,
    },
    {
        "id":"12",      
        "from": "Rubavu",
        "to": "Ngororero",
        "operate": "upCountry sides",
        "price": 3406,
    },
    {
        "id":"12",      
        "from": "Rubavu",
        "to": "Muhanga",
        "operate": "upCountry sides",
        "price": 3406,
    },
    {
        "id":"12",      
        "from": "Rubavu",
        "to": "Musanze",
        "operate": "upCountry sides",
        "price": 3406,
    },
    {
        "id":"12",      
        "from": "Rusizi",
        "to": "Nyabugogo",
        "operate": "upCountry sides",
        "price": 3406,
    },
    {
        "id":"12",      
        "from": "Rusizi",
        "to": "Nyamagabe",
        "operate": "upCountry sides",
        "price": 3406,
    },
    {
        "id":"12",      
        "from": "Rusizi",
        "to": "Nyamasheke",
        "operate": "upCountry sides",
        "price": 3406,
    },
    {
        "id":"12",      
        "from": "Rusizi",
        "to": "Karongi",
        "operate": "upCountry sides",
        "price": 3406,
    },
    {
        "id":"12",      
        "from": "Rusizi",
        "to": "Muhanga",
        "operate": "upCountry sides",
        "price": 3406,
    },
    {
        "id":"12",      
        "from": "Rusizi",
        "to": "Ruhango",
        "operate": "upCountry sides",
        "price": 3406,
    },
    {
        "id":"12",      
        "from": "Rusizi",
        "to": "Huye",
        "operate": "upCountry sides",
        "price": 3406,
    }
]